<?php

declare(strict_types=1);

namespace StaXr\Annotations\ORM;

use StaXr\Annotations\Interfaces\Annotation;

/**
 * Class AutoGenerated
 * @package StaXr\Annotations\ORM
 * @Annotation
 * @Target("PROPERTY")
 */
final class AutoGenerated implements Annotation
{
    /**
     * The type of Id generator.
     *
     * @Enum({"AUTOINCREMENT", "UUID", "CUSTOM"})
     */
    public string $strategy = 'AUTO';
}